name: Azure Login
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set environment variables
        run: |
          echo "RESOURCE_GROUP=${{ secrets[format('ADF_{0}_RESOURCE_GROUP', inputs.environment)] }}" >> $GITHUB_ENV
          echo "TARGET_FACTORY_NAME=${{ secrets[format('TARGET_FACTORY_NAME_{0}', inputs.environment)] }}" >> $GITHUB_ENV
          # Ajoute ici les autres variables spécifiques à l'environnement



